[package]
name = "meta-repo"
version = "0.1.8"
edition = "2021"

[dependencies]
clap = "4.5.18"
serde_json = "1.0.128"
config = "0.14.0"
serde = { version = "1.0.216", features = ["derive"] }
git2 = "0.19.0"
openssl = { version = "0.10.66", features = ["vendored"] }