[package]
name = "LIB-meta-repo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
serde_json = "1.0.117"
config = "0.14.0"
serde = { version = "1.0.203", features = ["derive"] }
git2 = "0.18.3"