on: [ push ]

name: CI

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests -- -D warnings

  rustfmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check the formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - rustfmt
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features